/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.12/userguide/building_java_projects.html in the Gradle documentation.
 */
import java.io.ByteArrayOutputStream

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    kotlin("jvm") version "2.1.10"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    maven(url = "https://jitpack.io")
    maven(url = "https://maven.lavalink.dev/releases")
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)

    implementation(kotlin("stdlib"))

    // Jakarta
    implementation("jakarta.annotation:jakarta.annotation-api:3.0.0")

    // JDA
    implementation("net.dv8tion:JDA:5.2.2")

    // Audio
    implementation("dev.arbjerg:lavaplayer:2.2.2")
    implementation("dev.lavalink.youtube:common:1.11.3")

    // HTTP requests
    implementation(platform("com.squareup.okhttp3:okhttp-bom:4.12.0"))
    implementation("com.squareup.okhttp3:okhttp")
    implementation("com.squareup.okhttp3:logging-interceptor")

    // JSON
    implementation("com.google.code.gson:gson:2.12.1")

    // SLF4J
    implementation("org.slf4j:slf4j-api:2.0.0-alpha5")
    implementation("org.slf4j:slf4j-simple:2.0.0-alpha5")

    // 
    // implementation("pw.aru.api:nekos4j:1.0")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
    modularity.inferModulePath = true 
}

application {
    // Define the main class for the application.
    // mainModule = "org.mofubot"
    mainClass = "org.mofubot.core.Mofubot"
}

tasks.withType<JavaCompile> {
    options.compilerArgs.addAll(listOf(
        "--add-reads", "org.mofubot=ALL-UNNAMED"
    ))
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

tasks.withType<JavaExec> {
    jvmArgs = listOf("--add-reads", "org.mofubot=ALL-UNNAMED")
}