/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.12/userguide/building_java_projects.html in the Gradle documentation.
 */
import java.io.ByteArrayOutputStream

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    kotlin("jvm") version "2.1.10"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    maven(url = "https://jitpack.io")
    maven(url = "https://maven.lavalink.dev/releases")
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)

    implementation(kotlin("stdlib"))

    implementation("net.dv8tion:JDA:5.2.2")
    implementation("dev.arbjerg:lavaplayer:2.2.2")
    implementation("dev.lavalink.youtube:common:1.11.3")
    implementation(platform("com.squareup.okhttp3:okhttp-bom:4.12.0"))
    implementation("com.squareup.okhttp3:okhttp")
    implementation("com.squareup.okhttp3:logging-interceptor")
    implementation("com.google.code.gson:gson:2.12.0")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
    // modularity.inferModulePath = true 
}

application {
    // Define the main class for the application.
    // mainModule = "org.mofubot"
    mainClass = "org.mofubot.Mofubot"
}

// tasks.register("findAutomaticModules") {
//     group = "verification"
//     description = "Finds automatic module names of all dependencies"

//     doLast {
//         val jdepsPath = "${System.getProperty("java.home")}/bin/jdeps"
//         val runtimeClasspath = configurations.runtimeClasspath.get().files

//         println("Analysing dependencies for automatic module names...")

//         runtimeClasspath.forEach { jar ->
//             if (jar.name.endsWith(".jar")) {
//                 val output = ByteArrayOutputStream()
//                 exec {
//                     commandLine(jdepsPath, "--module-path", configurations.runtimeClasspath.get().asPath, "-s", jar.absolutePath)
//                     standardOutput = output
//                     errorOutput = System.err
//                 }
//                 println("Dependency: ${jar.name}")
//                 println(output.toString().trim())
//                 println("-".repeat(80))
//             }
//         }
//     }
// }

// tasks.named("build") {
//     dependsOn("findAutomaticModules")
// }

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
