/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import org.mofubot.Mofubot;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        Mofubot classUnderTest = new Mofubot();
        // assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
