/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_mofubot_game_chess_ChessEngine */

#ifndef _Included_org_mofubot_game_chess_ChessEngine
#define _Included_org_mofubot_game_chess_ChessEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_mofubot_game_chess_ChessEngine
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_mofubot_game_chess_ChessEngine_initialise
  (JNIEnv *, jobject);

/*
 * Class:     org_mofubot_game_chess_ChessEngine
 * Method:    getBestMove
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_mofubot_game_chess_ChessEngine_getBestMove
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_mofubot_game_chess_ChessEngine
 * Method:    makeMove
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_mofubot_game_chess_ChessEngine_makeMove
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
